main: com.maximde.speedrun.Main
name: SpeedRun
version: 1.0.0
api-version: 1.0
description: Speedrun plugin
author: MaximDe

commands:
   reset:
      description: Reset all worlds!
   timer:
      description: The timer!
   time:
      description: Shows the current timer time!
   random:
         description: Random Things!