main: com.maximde.nextfight.main.MCBattleRoyale
name: NextFight
version: 1.0.0
api-version: 1.16
description: Official NextFight Plugin
author: MaximDe, KoKoKotlin
depend: [AdvancementsAPI]

commands:
   stats:
   start:
   help:
   advancements:
   setcape:
   mute:
   unmute:
   discord:
   rldata:
   l:
   lobby:
   spawn:
   resources:
   addtogame:
   connecttwitch:
   loststats:
   test: